spring:
  application:
    name: order
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://127.0.0.1/springcloud_sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  dev
label:
  release
